### PR TITLE
Ava/render patch

### PR DESCRIPTION
**Pull request by avahoffman**
Adding to #5 
@carriewright11 
- Images needed to be in "Day_3" module folder
- It was trying to render the `Manipulating_data_in_R` folder, which no longer had the images needed. So I deleted the old Data Cleaning, Manipulating Data, and Subsetting Data module folders (since these are now part of Day 3).. If we end up actually needing any of these, we can copy them over from https://github.com/jhudsl/intro_to_r/tree/main/modules

### CODE REVIEW

**Comment by carriewright11** [comment]
> Adding to #5 @carriewright11
> 
> * Images needed to be in "Day_3" module folder
> * It was trying to render the `Manipulating_data_in_R` folder, which no longer had the images needed. So I deleted the old Data Cleaning, Manipulating Data, and Subsetting Data module folders (since these are now part of Day 3).. If we end up actually needing any of these, we can copy them over from https://github.com/jhudsl/intro_to_r/tree/main/modules

ohhhh I seee what the problem was... I didn't remember putting the manipulating lecture in that folder :P

**Comment by carriewright11** [comment]
> > Adding to #5 @carriewright11
> > 
> > * Images needed to be in "Day_3" module folder
> > * It was trying to render the `Manipulating_data_in_R` folder, which no longer had the images needed. So I deleted the old Data Cleaning, Manipulating Data, and Subsetting Data module folders (since these are now part of Day 3).. If we end up actually needing any of these, we can copy them over from https://github.com/jhudsl/intro_to_r/tree/main/modules
> 
> ohhhh I seee what the problem was... I didn't remember putting the manipulating lecture in that folder :P

because I decided to keep it for day 4 - it was late haha

**Comment by carriewright11** [comment]
because I had all my images in that folder for subsetting and cleaning

**Comment by avahoffman** [comment]
Glad we figured it out!

**Comment by carriewright11** [comment]
> Glad we figured it out!

yes- thanks to you!!

**Comment by carriewright11** [comment]
Going to close this since I moved the files around in the other PR to make day 4

**Pull request closed without merging**
